### ISSUE TITLE
Leptos dep with "tracing" feature enabled leads to build error

### ISSUE THREAD

**Issue by lpotthast** [carloskiki/leptos-icons#1]
If a user of leptos-icons enables the "tracing" feature of Leptos in his own crate, the build will fail, as the #[component] macro used for all the icon-components cannot find the tracing crate inside leptos-icons. Adding the tracing dependency to leptos-icons, probably behind a similarly named feature should fix that error.

**Comment by lpotthast** [comment]
I'm working on a larger change and will submit a PR.

**Comment by carloskiki** [comment]
Okay great, I was not aware of this bug. I have also worked a bit on the library without pushing the changes as they do not work correctly. Most notably:
- using `quote!` macro to generate the code for each icon
- using the `prettyplease` crate to prettify the generated code.
- Added support for some basic props: size, class, colour, style, and title.

I'll await your reply before pushing my changes as they introduce bugs and you may have a better solution.

**Comment by carloskiki** [comment]
I have decided to push the changes as they now work. Feel free to suggest big changes, I'm very open to changing the way the library is currently structured.

**Comment by carloskiki** [comment]
I will close this issue as it is now resolved.
