### ISSUE TITLE
Not compatible with leptos v4.0.0 +

### ISSUE THREAD

**Issue by MinaMatta98** [carloskiki/leptos-icons#16]

**Comment by jsprog** [comment]
When building in release mode with trunk and leptos@0.4.1 `trunk build --release`, I'm receiving this error:

the trait `leptos::Component<_>` is not implemented for fn item `fn(leptos_reactive::scope::Scope, IconProps<_>) -> impl leptos_dom::IntoView {leptos_icons::Icon::<_>}`

**Comment by MinaMatta98** [comment]
This is also the case with cargo leptos.

**Comment by lpotthast** [comment]
This is expected, as only the Component trait from Leptos 0.3 is implemented for the icon component function when you depend on a version of leptos-icons targeting leptos 0.3 and target leptos 0.4 yourself. Different versions of the same type are present when compilation runs leading to this kind of error.

**Comment by MinaMatta98** [comment]
Is there a version which targets 4.0+?

**Comment by lpotthast** [comment]
Made a PR for it. Until released as leptos-icons 0.0.15, you can already try it out using
```
leptos-icons = { git = "https://github.com/lpotthast/leptos-icons", branch = "leptos_0.4", features = [
    // ...
] }
```

**Comment by carloskiki** [comment]
This is closed by #17

**Comment by MinaMatta98** [comment]
Thank you 😊

**Comment by jsprog** [comment]
FYI: Usually, I don't depend on non release dependencies unless I faced some blockers. Unfortunately,  leptos-icons@0.0.15 is broken again with the git dependency of leptos

based on [examples/simple-app](https://github.com/Carlosted/leptos-icons/tree/main/examples/simple-app), replace leptos dependency to `# leptos = { git = "https://github.com/leptos-rs/leptos", features = ["csr"] }` and build again to receive these errors:

the trait `ComponentConstructor<_>` is not implemented for `&fn(leptos_reactive::scope::Scope, IconProps) -> impl leptos_dom::IntoView {leptos_icons::Icon}`

the trait `leptos::Component<_>` is not implemented for fn item `fn(leptos_reactive::scope::Scope, IconProps) -> impl leptos_dom::IntoView {leptos_icons::Icon}`
