### ISSUE TITLE
the crate `leptos_icons@0.0.15` could not be found in registry index.

### ISSUE THREAD

**Issue by jsprog** [carloskiki/leptos-icons#18]
leptos_icons@0.0.15 that's compatible with leptos@4.x.x isn't published since the last change is Readme.md about a week ago.

Please, try `cargo add leptos_icons@0.0.15` to confirm.

![image10](https://github.com/Carlosted/leptos-icons/assets/3159108/e90e6b91-44da-4ffa-90de-c29ec02124c0)

**Comment by lpotthast** [comment]
@Carlosted Can you release v0.0.15?

**Comment by carloskiki** [comment]
Thank you for tagging me! I totally missed this notification. 0.0.15 is now live.
