### ISSUE TITLE
Support for stable leptos

### ISSUE THREAD

**Issue by jmintb** [carloskiki/leptos-icons#2]
Awesome crate :fire: 

I can't build leptos-icons on stable Rust and I don't see a stable feature to enable it.

Are you interested in adding a stable feature, which could be passed to the leptos so it builds on stable Rust?

I can submit a PR if you would like.

**Comment by carloskiki** [comment]
Yes of course! this is definitely a crucial feature. Do submit a PR and do not hesitate to ask if you have any questions.

**Comment by carloskiki** [comment]
I will close this pr as stable rust is now supported by default.

Always feel free to reopen an issue.

**Comment by jmintb** [comment]
Awesome :+1:
