### ISSUE TITLE
Implement From of each of the icon types for MaybeSignal<Icon>

### ISSUE THREAD

**Issue by SleeplessOne1917** [carloskiki/leptos-icons#22]
[I tried something like this for the icondata crate not long ago](https://github.com/Carlosted/icondata/pull/18) and was told that that crate was supposed to be framework agnostic. This seems like the more appropriate repo for that change.

I was having trouble getting the `icon!` macro to work. While that would solve the issues I'm having, I noticed that using `Icon::From` worked as well. If `From` is implemented on the icon types, it should allow consumers of the library to pass their directly to the icon component, making the `icon!` macro superfluous.

I'm willing to implement this change. @Carlosted Are the features generated programmatically for this crate like they are for the icondata crate?

**Comment by carloskiki** [comment]
> [I tried something like this for the icondata crate not long ago](https://github.com/Carlosted/icondata/pull/18) and was told that that crate was supposed to be framework agnostic. This seems like the more appropriate repo for that change.

Yes this is the right place to implement this feature!

> I was having trouble getting the `icon!` macro to work. While that would solve the issues I'm having, I noticed that using `Icon::From` worked as well. If `From` is implemented on the icon types, it should allow consumers of the library to pass their directly to the icon component, making the `icon!` macro superfluous.

It would indeed be great if we find a way to remove the `icon!` macro for something better.

> I'm willing to implement this change. @Carlosted Are the features generated programmatically for this crate like they are for the icondata crate?

I have not found enough time recently to work on a cli for this, but the features are generated programmatically in the [boilerplate folder](https://github.com/Carlosted/icondata/blob/main/boilerplate/Cargo.toml) of the icondata repo.

I should be able to take a look at your PR (#23) later today.

**Comment by carloskiki** [comment]
Let me know if you need help with the `icon!` macro.
