### ISSUE TITLE
The index of the Icons is void

### ISSUE THREAD

**Issue by gustavojoaquin** [carloskiki/leptos-icons#34]
hi, when i enter to the link i can't see nothing, just a blank page
![image](https://github.com/Carlosted/leptos-icons/assets/93671143/a9725d3d-acec-4751-929d-35c7592c65bb)

**Comment by carloskiki** [comment]
Can you show what's going on in console and network tab?

**Comment by s1n7ax** [comment]
@Carlosted 404

![image](https://github.com/Carlosted/leptos-icons/assets/18459807/895d2e2d-128d-4e32-9b80-c9d1affb5aac)
