### ISSUE TITLE
Explain in the readme how to not compile all icons

### ISSUE THREAD

**Issue by IongIer** [carloskiki/leptos-icons#43]
Please include more info in the readme about how to use the libs especially if there is a way to not include all the icons from icondata when compiling debug builds.

**Comment by carloskiki** [comment]
According to every size test I have done, all icons are not included in `debug` builds either.

You can test the size of the generated `wasm` file by using `twiggy` for instance. If you can show me that all icons are included in debug builds, then we can look at what the issue is.
