### ISSUE TITLE
What is the type of Icon & icondata?

### ISSUE THREAD

**Issue by s1n7ax** [carloskiki/leptos-icons#44]
I'm new to rust but it seems icon type is not exposed. My requirement is to store a list of icons in an array and use a loop to show all of them. But I couldn't get it working because the `icondata_core::IconData` type is not exposed from the lib. Is it possible to store a list of either `leptos_icons::Icon`s or `icondata_core::IconData`? If so what would be the type of the array?

**Comment by carloskiki** [comment]
You should be able to use the `Icon` type Alias. Basically `Icon` is a reference to a `IconData`, which is what you want. Every Icon is has the `Icon` type (you can see it as a pointer to the data).

**Comment by s1n7ax** [comment]
Thanks! `icondata::Icon` works.
