### ISSUE TITLE
Use with tailwind

### ISSUE THREAD

**Issue by tversteeg** [carloskiki/leptos-icons#52]
How can I apply Tailwind classes on the icon? In the previous version (0.3.x), I could do something like this:

```html
<Icon icon={icondata::FaCalendarDaysSolid} class="w-4 h-4 text-gray-600" />
```

But this doesn't work anymore since `class` is not exposed.

**Comment by ozpv** [comment]
> How can I apply Tailwind classes on the icon? In the previous version (0.3.x), I could do something like this:
> 
> ```
> <Icon icon={icondata::FaCalendarDaysSolid} class="w-4 h-4 text-gray-600" />
> ```
> 
> But this doesn't work anymore since `class` is not exposed.

It's no longer necessary to include a class prop in 0.7. Use spreading instead:

```rust
<Icon icon={icondata::FaCalendarDaysSolid} {..} class="w-4 h-4 text-gray-600" />
```

**Comment by carloskiki** [comment]
@ozpv's answer is correct, thus I will close this issue.

**Comment by NCura** [comment]
Just to share a tip in case anyone encounters issues with **Leptosfmt** removing the  `..` from this syntax:  

```rust
<Icon icon={icondata::FaCalendarDaysSolid} {..} class="w-4 h-4 text-gray-600" />
```  

An alternative approach you can use is:  

```rust
<Icon icon=icondata::FaCalendarDaysSolid attr:class="w-4 h-4 text-gray-600" />
```  

For reference, a PR has already been accepted in **Leptosfmt** to address this issue. However, as of today, a release has not yet been created.
