### ISSUE TITLE
Library (re)naming

### ISSUE THREAD

**Issue by lpotthast** [carloskiki/leptos-icons#6]
`leptos-icons`, as the library is currently named, more or less clashes with https://crates.io/crates/leptos_icons. Publishing this crate under `leptos-icons` (I think that might be possible, as it uses a dash instead of an underscore, but I'm not 100% sure on that) might not be a good idea, as users will likely use the wrong library. Or we can't use the name in the first place.

I would suggest finding a different name for the library.

**Comment by lpotthast** [comment]
Suggestion from having a brief talk to ChatGPT:

> `lepticons` is a good option for the name of your icon library because it is a play on words that incorporates "Leptos" and "icons" in a memorable and concise way. The name is easy to pronounce and spell, making it easy to remember and share with others.
> 
> In addition, the name "Lepticons" has a certain visual appeal and evokes the idea of small, compact and sleek icons, which can be a great fit for a web UI framework like leptos.
> 
> Finally, since your icon library is specifically designed for leptos, it's important to have a name that reflects that relationship. Using "Lepticons" as the name of your icon library makes it clear that it is designed to be used specifically with the leptos web framework.

**Comment by carloskiki** [comment]
Yes, I am very aware of that, and after testing, crates.io treats this crate's name as identical to https://crates.io/crates/leptos_icons. I have been trying to contact the author of this crate without success throughout the week, which means that we should probably consider other names.

One Idea was to submit different crates for every icon package (as you mentioned in your pull request) which would work, but I'm worried that the names are still too similar to avoid confusion.

The name you proposed is really clear and symbolic, but I also liked the leptos naming convention i.e.: `leptos_reactive`, `leptos_dom`, `leptos_server` ...

After a quick chat with ChatGPT, the names `leptos_iconic` and `leptos_pictos` were the ones that I preferred, but they are not as clear as your suggestion.

What do you think?

**Comment by carloskiki** [comment]
We could also use the same name convention as dioxus: "leptos-free-icons"

**Comment by carloskiki** [comment]
With further thinking, I have settled on `leptos_glyphs`, as it follows the leptos naming convention, and because glyph has Greek origins, just like leptos is a Greek word.

**Comment by carloskiki** [comment]
This issue is now solved as we have access to the leptos_icons name.
